add ellipse fit
AntSimi/py-eddy-tracker pull request #77
Opened 2021-04-01 15:03 UTC by CoriPegliasco

- minor english modifs

2021-04-01 19:11 UTC, AntSimi commented
Lint found some incorrect things

2021-04-01 19:15 UTC, AntSimi requested changes
Correct error raise by lint and add some extra comment about fitted ellipse

2021-04-01 19:15 UTC, AntSimi commented on examples/16_network/pet_ioannou_2017_case.py
> +
Maybe add some extra comment :)

2021-04-06 12:49 UTC, CoriPegliasco commented
Hope it works know!

2021-04-06 12:55 UTC, AntSimi approved these changes

2021-04-06 12:55 UTC, merged