update coherence forward/backward
AntSimi/py-eddy-tracker pull request #96
Opened 2021-06-18 09:28 UTC by ludwigVonKoopa

2021-06-18 13:29 UTC, AntSimi requested changes
some warning with flake8
./src/py_eddy_tracker/observations/network.py:1476:128: E501 line too long (139 > 127 characters)
./src/py_eddy_tracker/observations/network.py:1539:128: E501 line too long (139 > 127 characters)
./examples/07_cube_manipulation/pet_fsle_med.py:30:56: W291 trailing whitespace
./examples/16_network/pet_follow_particle.py:19:1: F401 'py_eddy_tracker.poly.group_obs' imported but unused

2021-06-18 13:29 UTC, AntSimi commented on src/py_eddy_tracker/observations/groups.py
> +    """create particles only inside speed contour. Avoir creating too large numpy arrays, only to me masked
Avoir?

2021-06-21 10:36 UTC, ludwigVonKoopa commented on src/py_eddy_tracker/observations/groups.py
> +    """create particles only inside speed contour. Avoir creating too large numpy arrays, only to me masked
mistake

2021-06-21 19:39 UTC, ludwigVonKoopa commented
better create_particles

some differences exists with new version, as old version sometimes created double particles (2 different particles with same lon/lat).
Bounding box were squared and chosen a little bit over min/max, so if 2 eddy were close enough and with proper shape, there was chances to create double particles

2021-06-21 20:49 UTC, AntSimi approved these changes

2021-06-22 08:06 UTC, merged